### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by Scarlet-K** [Scarlet-K/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] create an `index.html`
- [x] create a `styles.css`
- [x] link the `styles.css` files to the` .html`
- [x] set the `body`'s color to green
